FROM python:3.10-slim

# Install dependencies for dlib and face-recognition
RUN apt-get update && apt-get install -y \
    build-essential cmake \
    libopenblas-dev liblapack-dev \
    libx11-dev libgtk-3-dev \
    libboost-all-dev \
    && rm -rf /var/lib/apt/lists/*

# Set working dir
WORKDIR /app

# Copy requirements
COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy project
COPY . .

# Env vars
ENV PORT=8080
ENV FLASK_ENV=production

# Run gunicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "app:app"]
